/*------------------------------------------------部门管理-------------------------------*/
$('.choseQuerydept').on('click',function(){
	$('.query_dept').show();
	$('.add_dept').hide();
	$('.hide_adddiv').remove();
});
$('.choseAdddept').on('click',function(){
	$('.add_dept').show();
	$('.query_dept').hide();
	$('.hide_adddiv').remove();
});

/*-------------------------------------------------岗位管理------------------------------*/
$('.choseQueryjob').on('click',function(){
	$('.query_job').show();
	$('.add_job').hide();
	$('.hide_adddiv').remove();
});
$('.choseAddjob').on('click',function(){
	$('.add_job').show();
	$('.query_job').hide();
	$('.hide_adddiv').remove();
});

/*-------------------------------------------------员工管理------------------------------*/
$('.choseQueryemp').on('click',function(){
	$('.query_emp').show();
	$('.add_emp').hide();
	$('.hide_adddiv').remove();
});
$('.choseAddemp').on('click',function(){
	$('.add_emp').show();
	$('.query_emp').hide();
	$('.hide_adddiv').remove();
});

/*-------------------------------------------------固定工资管理------------------------------*/
$('.choseQuery_regularsal').on('click',function(){
	$('.query_regularsal').show();
	$('.updata_regularsal').hide();
	$('.hide_adddiv').remove();
});
$('.choseUpdata_regularsal').on('click',function(){
	$('.updata_regularsal').show();
	$('.query_regularsal').hide();
	$('.hide_adddiv').remove();
});

/*-------------------------------------------------导入项目管理------------------------------*/
$('.choseQuery_enterdata').on('click',function(){
	$('.query_enterdata').show();
	$('.updata_enterdata').hide();
	$('.hide_adddiv').remove();
});
$('.choseUpdata_enterdata').on('click',function(){
	$('.updata_enterdata').show();
	$('.query_enterdata').hide();
	$('.hide_adddiv').remove();
});

/*-------------------------------------------------工资结算------------------------------------------*/
